export const ACTION_ONLINE_NEWS_PRE_FETCH = "ACTION_ONLINE_NEWS_PRE_FETCH"
export const ACTION_ONLINE_NEWS_FETCH_OK = "ACTION_ONLINE_NEWS_FETCH_OK"
export const ACTION_ONLINE_NEWS_FETCH_ERROR ="ACTION_ONLINE_NEWS_FETCH_ERROR"
