export const ACTION_ONLINE_NEWS_PRE_FETCH = "ACTION_ONLINE_NEWS_PRE_FETCH"
export const ACTION_ONLINE_NEWS_FETCH_OK = "ACTION_ONLINE_NEWS_FETCH_OK"
export const ACTION_ONLINE_NEWS_FETCH_ERROR ="ACTION_ONLINE_NEWS_FETCH_ERROR"


export const ACTION_OCG_NEWS_PRE_FETCH="ACTION_OCG_NEWS_PRE_FETCH"
export const ACTION_OCG_NEWS_FETCH_OK = "ACTION_OCG_NEWS_FETCH_OK"
export const ACTION_OCG_NEWS_FETCH_ERROR = "ACTION_OCG_NEWS_FETCH_ERROR"


export const ACTION_GONGLUE_NEWS_PRE_FETCH="ACTION_GONGLUE_NEWS_PRE_FETCH"
export const ACTION_GONGLUE_NEWS_FETCH_OK = "ACTION_GONGLUE_NEWS_FETCH_OK"
export const ACTION_GONGLUE_NEWS_FETCH_ERROR = "ACTION_GONGLUE_NEWS_FETCH_ERROR"


export const ACTION_CARD_NEWS_PRE_FETCH="ACTION_CARD_NEWS_PRE_FETCH"
export const ACTION_CARD_NEWS_FETCH_OK = "ACTION_CARD_NEWS_FETCH_OK"
export const ACTION_CARD_NEWS_FETCH_ERROR = "ACTION_CARD_NEWS_FETCH_ERROR"


export const ACTION_VIDEO_NEWS_PRE_FETCH="ACTION_VIDEO_NEWS_PRE_FETCH"
export const ACTION_VIDEO_NEWS_FETCH_OK = "ACTION_VIDEO_NEWS_FETCH_OK"
export const ACTION_VIDEO_NEWS_FETCH_ERROR = "ACTION_VIDEO_NEWS_FETCH_ERROR"